SPOOL ./create_schema_ora.log

-- SYSTEM PRIVILEGES TO CREATE TABLE IN OWN SCHEMA
GRANT CREATE TABLE TO &&1;


-- Add STATUS and STEP columns 

CREATE OR REPLACE FORCE VIEW &&1..MYREPRESENTATIVEJOBS (
                                    "JOBID", "JOBGUID", "REPRESENTATIVEUSERID", 
                                    "REPRESENTEDUSERID", "DOWNLOADCOUNT", "CREATEDDATE", 
                                    "REPRESENTATIVEUSERFIRSTNAME", "REPRESENTATIVEUSERLASTNAME", "REPRESENTATIVEUSERCOMPANY", 
                                    "REPRESENTATIVEUSEREMAIL", "REPRESENTEDUSERFIRSTNAME", "REPRESENTEDUSERLASTNAME", 
                                    "REPRESENTEDUSERCOMPANY", "REPRESENTEDUSEREMAIL", "ISARCHIVED", 
                                    "CUSTOM1", "CUSTOM2", "CUSTOM3", 
                                    "CUSTOM4", "CUSTOM5", "CUSTOM6", 
                                    "CUSTOM7", "CUSTOM8", "CUSTOM9", 
                                    "CUSTOM10", "PARCELNUMBER", "REASONID", "REASON", 
                                    "STATUS", "GNSD_JOBS.STEP")
    AS
SELECT    GNSD_JOBS.JOBID, 
          GNSD_JOBGUID.JOBGUID, 
          GNSD_SURROGATE_JOBS.SURROGATEUSERID AS REPRESENTATIVEUSERID, 
          GNSD_JOBS.USERID AS REPRESENTEDUSERID, 
          GNSD_JOBS.DOWNLOADCOUNT, 
          CREATEDDATE AS CREATEDDATE, 
          GNSD_USERS.FIRSTNAME AS REPRESENTATIVEUSERFIRSTNAME, 
          GNSD_USERS.LASTNAME AS REPRESENTATIVEUSERLASTNAME, 
          GNSD_USERS.COMPANY AS REPRESENTATIVEUSERCOMPANY, 
          GNSD_USERS.EMAIL AS REPRESENTATIVEUSEREMAIL, 
          GNSD_USERS_1.FIRSTNAME AS REPRESENTEDUSERFIRSTNAME, 
          GNSD_USERS_1.LASTNAME AS REPRESENTEDUSERLASTNAME, 
          GNSD_USERS_1.COMPANY AS REPRESENTEDUSERCOMPANY, 
          GNSD_USERS_1.EMAIL AS REPRESENTEDUSEREMAIL, 
          GNSD_JOBS.ISARCHIVED,
          GNSD_JOBS.CUSTOM1, GNSD_JOBS.CUSTOM2, GNSD_JOBS.CUSTOM3, 
          GNSD_JOBS.CUSTOM4, GNSD_JOBS.CUSTOM5, GNSD_JOBS.CUSTOM6, 
          GNSD_JOBS.CUSTOM7, GNSD_JOBS.CUSTOM8, GNSD_JOBS.CUSTOM9, 
          GNSD_JOBS.CUSTOM10, GNSD_JOBS.PARCELNUMBER, 
          GNSD_JOBS.REASONID, GNSD_REASONS.DESCRIPTION AS REASON,
          GNSD_JOBS.STATUS, GNSD_JOBS.STEP
FROM         
           &&1..GNSD_REASONS INNER JOIN
           &&1..GNSD_JOBS INNER JOIN
           &&1..GNSD_USERS GNSD_USERS_1 ON GNSD_JOBS.USERID = GNSD_USERS_1.USERID ON 
           &&1..GNSD_REASONS.REASONID = &&1..GNSD_JOBS.REASONID LEFT OUTER JOIN
           &&1..GNSD_JOBGUID ON GNSD_JOBS.JOBID = GNSD_JOBGUID.JOBID LEFT OUTER JOIN
           &&1..GNSD_USERS INNER JOIN
           &&1..GNSD_SURROGATE_JOBS ON GNSD_USERS.USERID = GNSD_SURROGATE_JOBS.SURROGATEUSERID ON 
           GNSD_JOBS.JOBID = GNSD_SURROGATE_JOBS.JOBID LEFT OUTER JOIN
               (SELECT JOBID AS JOBID, MIN(TIMESTAMP) AS CREATEDDATE
                 FROM &&1..GNSD_JOBS_LOG
                 GROUP BY JOBID) LOGS ON GNSD_JOBS.JOBID = LOGS.JOBID

/
COMMIT
/
SPOOL OFF
QUIT