SPOOL ./create_schema_ora.log

-- SYSTEM PRIVILEGES TO CREATE TABLE IN OWN SCHEMA
GRANT CREATE TABLE TO &&1;


-- Add two new columns to the GNSD_JOBS table
ALTER TABLE &&1..GNSD_JOBS
    ADD (STATEDATE DATE NULL,
		CREATEDATE DATE NULL)

/
COMMIT
/

-- Simplify view to make it faster
CREATE OR REPLACE FORCE VIEW &&1..GNSD_GRIDJOBVIEW ("JOBID", "STATEDATE", "CREATEDATE", "USERID", "REASONID", "REASON", "JOBOUTPUT", "DEFINITION", "CUSTOM1", "CUSTOM2", "CUSTOM3", "CUSTOM4", "CUSTOM5", "CUSTOM6", "CUSTOM7", "CUSTOM8", "CUSTOM9", "CUSTOM10", "STEP", "STATUS", "NEEDSPROCESSING", "ISACTIVE", "PROCESSID", "MACHINENAME", "PROCESSING_USERID", "PROCESSOR_CLASSID", "ISARCHIVED", "PERIODBEGINDATE", "PERIODENDDATE", "DESCRIPTION", "PARCELNUMBER", "MUNICIPALITY", "CENTERAREAX", "CENTERAREAY", "DOWNLOADCOUNT", "MAPEXTENTCOUNT", "GEOATTACHMENTSENABLED", "SURROGATEUSERID", "REQUESTDATE", "REQUESTTYPE", "STOPAFTERPROCESS", "FIRSTNAME", "LASTNAME", "EMAIL")
AS
  SELECT GNSD_JOBS.JOBID,
    GNSD_JOBS.STATEDATE,
    GNSD_JOBS.CREATEDATE,
    GNSD_JOBS.USERID,
    GNSD_JOBS.REASONID,
    GNSD_REASONS.DESCRIPTION AS REASON,
    GNSD_JOBS.JOBOUTPUT,
    GNSD_JOBS.DEFINITION,
    GNSD_JOBS.CUSTOM1,
    GNSD_JOBS.CUSTOM2,
    GNSD_JOBS.CUSTOM3,
    GNSD_JOBS.CUSTOM4,
    GNSD_JOBS.CUSTOM5,
    GNSD_JOBS.CUSTOM6,
    GNSD_JOBS.CUSTOM7,
    GNSD_JOBS.CUSTOM8,
    GNSD_JOBS.CUSTOM9,
    GNSD_JOBS.CUSTOM10,
    GNSD_JOBS.STEP,
    GNSD_JOBS.STATUS,
    GNSD_JOBS.NEEDSPROCESSING,
    GNSD_JOBS.ISACTIVE,
    GNSD_JOBS.PROCESSID,
    GNSD_JOBS.MACHINENAME,
    GNSD_JOBS.PROCESSING_USERID,
    GNSD_JOBS.PROCESSOR_CLASSID,
    GNSD_JOBS.ISARCHIVED,
    GNSD_JOBS.PERIODBEGINDATE,
    GNSD_JOBS.PERIODENDDATE,
    GNSD_JOBS.DESCRIPTION,
    GNSD_JOBS.PARCELNUMBER,
    GNSD_JOBS.MUNICIPALITY,
    GNSD_JOBS.CENTERAREAX,
    GNSD_JOBS.CENTERAREAY,
    GNSD_JOBS.DOWNLOADCOUNT,
	GNSD_JOBS.MAPEXTENTCOUNT,
	GNSD_JOBS.GEOATTACHMENTSENABLED,
    GNSD_SURROGATE_JOBS.SURROGATEUSERID,
    GNSD_SURROGATE_JOBS.REQUESTDATE,
    GNSD_SURROGATE_JOBS.REQUESTTYPE,
    GNSD_SURROGATE_JOBS.STOPAFTERPROCESS,
    GNSD_USERS.FIRSTNAME,
    GNSD_USERS.LASTNAME,
    GNSD_USERS.EMAIL
  FROM &&1..GNSD_JOBS LEFT OUTER JOIN &&1..GNSD_USERS ON GNSD_JOBS.USERID = GNSD_USERS.USERID
    LEFT OUTER JOIN &&1..GNSD_REASONS ON GNSD_JOBS.REASONID = GNSD_REASONS.REASONID
    LEFT OUTER JOIN &&1..GNSD_SURROGATE_JOBS ON GNSD_JOBS.JOBID = GNSD_SURROGATE_JOBS.JOBID

/
COMMIT
/

CREATE OR REPLACE TRIGGER &&1..TRG_GNSD_JOB_LOG_STATEDATE
	AFTER INSERT ON &&1..GNSD_JOBS_LOG
	FOR EACH ROW
	BEGIN
	  UPDATE &&1..GNSD_JOBS
	  SET STATEDATE = :new.TIMESTAMP
	  WHERE JOBID = :new.JOBID;
	END TRG_GNSD_JOB_LOG_STATEDATE;

/
COMMIT;
/

-- make queries on jobs faster. Columns PROCESSOR_CLASSID and ISARCHIVED are used 
CREATE INDEX &&1..GNSD_JOBS_CLASSID_ARCHIVED ON &&1..GNSD_JOBS ("PROCESSOR_CLASSID", "ISARCHIVED") ;

/
COMMIT;
/


-- Recalculate values of the STATEDATE and CREATEDATE columns for every job
-- !!!This might take couple minutes to complete!!!
 UPDATE &&1..GNSD_JOBS
 SET CREATEDATE = (SELECT MIN(TIMESTAMP) FROM &&1..GNSD_JOBS_LOG WHERE &&1..GNSD_JOBS_LOG.JOBID = &&1..GNSD_JOBS.JOBID),
 STATEDATE = (SELECT MAX(TIMESTAMP) FROM &&1..GNSD_JOBS_LOG WHERE &&1..GNSD_JOBS_LOG.JOBID = &&1..GNSD_JOBS.JOBID);

/
COMMIT;
/

-- Change the type of the Definition column to be capable of storing more that 4000 characters and so more plots. 
-- Alternation from VARCHAR2(4000) to NCLOB is not possible and must by done via a temporary column.
ALTER TABLE &&1..GNSD_JOBS 
ADD DEFINITION_NEW NCLOB;

UPDATE &&1..GNSD_JOBS  
SET DEFINITION_NEW = DEFINITION;

ALTER TABLE &&1..GNSD_JOBS 
DROP COLUMN DEFINITION;

ALTER TABLE &&1..GNSD_JOBS 
RENAME COLUMN DEFINITION_NEW To DEFINITION;

/
COMMIT;
/

SPOOL OFF
QUIT