//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEOCOM.GNSD.Web {
    
    
    public partial class RequestPage {
        
        /// <summary>
        /// MostTopElementPlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder MostTopElementPlaceHolder;
        
        /// <summary>
        /// hfMapExtents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfMapExtents;
        
        /// <summary>
        /// ctlSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GEOCOM.GNSD.Web.Controls.DefaultMapSearch ctlSearch;
        
        /// <summary>
        /// ctlActAsSurrogate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GEOCOM.GNSD.Web.Controls.CommonActAsSurrogate ctlActAsSurrogate;
        
        /// <summary>
        /// ctlPlotLayout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GEOCOM.GNSD.Web.Controls.MorphingControl ctlPlotLayout;
        
        /// <summary>
        /// ctlExportProfileSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GEOCOM.GNSD.Web.Controls.MorphingControl ctlExportProfileSelector;
        
        /// <summary>
        /// ExportTypeSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GEOCOM.GNSD.Web.Controls.ExportTypeSelector ExportTypeSelector;
        
        /// <summary>
        /// ctlRequestDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GEOCOM.GNSD.Web.Controls.CommonRequestDetails ctlRequestDetails;
        
        /// <summary>
        /// PlotModeMap control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GEOCOM.GNSD.Web.Controls.MorphingControl PlotModeMap;
        
        /// <summary>
        /// DataModeMap control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GEOCOM.GNSD.Web.Controls.MorphingControl DataModeMap;
        
        /// <summary>
        /// placeHolderPlotSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder placeHolderPlotSection;
        
        /// <summary>
        /// lblAvailablePlotSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblAvailablePlotSection;
    }
}
