USE [$(geodatabase)]
GO

/****** Object:  View [$(gnsduser)].[GNSD_GRIDJOBVIEW]    Script Date: 08.09.2016 18:43:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER TABLE [$(gnsduser)].[GNSD_JOBS]
	ADD 
    [MACHINENAME] [nvarchar](255) NULL,
	[CUSTOM4] [nvarchar](max) NULL,
	[CUSTOM5] [nvarchar](max) NULL,
	[CUSTOM6] [nvarchar](max) NULL,
	[CUSTOM7] [nvarchar](max) NULL,
	[CUSTOM8] [nvarchar](max) NULL,
	[CUSTOM9] [nvarchar](max) NULL,
	[CUSTOM10] [nvarchar](max) NULL

GO

ALTER VIEW [$(gnsduser)].[GNSD_GRIDJOBVIEW] AS SELECT
      GNSD_JOBS.JOBID,
      STATEDATE,
      CREATEDATE,
      GNSD_JOBS.USERID,
      GNSD_JOBS.REASONID,
      GNSD_REASONS.DESCRIPTION AS REASON,
      GNSD_JOBS.JOBOUTPUT,
      GNSD_JOBS.DEFINITION,
      GNSD_JOBS.CUSTOM1,
      GNSD_JOBS.CUSTOM2,
      GNSD_JOBS.CUSTOM3,
      GNSD_JOBS.CUSTOM4,
      GNSD_JOBS.CUSTOM5,
      GNSD_JOBS.CUSTOM6,
      GNSD_JOBS.CUSTOM7,
      GNSD_JOBS.CUSTOM8,
      GNSD_JOBS.CUSTOM9,
      GNSD_JOBS.CUSTOM10,
      GNSD_JOBS.STEP,
      GNSD_JOBS.STATUS,
      GNSD_JOBS.NEEDSPROCESSING,
      GNSD_JOBS.ISACTIVE,
      GNSD_JOBS.PROCESSID,
	  GNSD_JOBS.MACHINENAME,
      GNSD_JOBS.PROCESSING_USERID,
      GNSD_JOBS.PROCESSOR_CLASSID,
      GNSD_JOBS.ISARCHIVED,
      GNSD_JOBS.PERIODBEGINDATE, 
      GNSD_JOBS.PERIODENDDATE,
      GNSD_JOBS.DESCRIPTION,
      GNSD_JOBS.PARCELNUMBER,
      GNSD_JOBS.MUNICIPALITY,
      GNSD_JOBS.CENTERAREAX,
      GNSD_JOBS.CENTERAREAY,
      GNSD_JOBS.DOWNLOADCOUNT,
	  GNSD_JOBS.MAPEXTENTCOUNT,
	  GNSD_JOBS.GEOATTACHMENTSENABLED,
      GNSD_SURROGATE_JOBS.SURROGATEUSERID,
      GNSD_SURROGATE_JOBS.REQUESTDATE,
      GNSD_SURROGATE_JOBS.REQUESTTYPE,
      GNSD_SURROGATE_JOBS.STOPAFTERPROCESS,
      GNSD_USERS.FIRSTNAME,
      GNSD_USERS.LASTNAME,
      GNSD_USERS.EMAIL     
      FROM
      ((GNSD_JOBS left outer join
      (SELECT
      GNSD_JOBS_LOG.JOBID AS ID,
      MAX(TIMESTAMP) AS STATEDATE,
      MIN(TIMESTAMP) AS CREATEDATE
      FROM
      GNSD_JOBS_LOG
      GROUP BY
      JOBID) AS LOGS on GNSD_JOBS.JOBID = LOGS.ID)
        left outer join GNSD_USERS on GNSD_JOBS.USERID = GNSD_USERS.USERID) 
        left outer join GNSD_REASONS on GNSD_JOBS.REASONID = GNSD_REASONS.REASONID
        left outer join GNSD_SURROGATE_JOBS on GNSD_JOBS.JOBID = GNSD_SURROGATE_JOBS.JOBID

        
GO
