/* see demand http://dtrack.geo.esri-de.net/view.php?id=10969
** This script adds a new column MapExtentCount to the [gnsd_jobs] table and the [GNSD_GRIDJOBVIEW].
*/

USE [gnsd_myp_TEST]
GO

/****** Object:  Table [gnsd_de].[gnsd_jobs]    Script Date: 04/03/2012 14:04:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

ALTER TABLE [gnsd_de].[gnsd_jobs]
	ADD MapExtentCount [int] NULL
GO

ALTER VIEW [gnsd_de].[GNSD_GRIDJOBVIEW] AS SELECT
      GNSD_JOBS.JOBID,
      STATEDATE,
      CREATEDATE,
      GNSD_JOBS.USERID,
      GNSD_JOBS.REASONID,
      GNSD_REASONS.DESCRIPTION AS REASON,
      GNSD_JOBS.JOBOUTPUT,
      GNSD_JOBS.DEFINITION,
      GNSD_JOBS.CUSTOM1,
      GNSD_JOBS.CUSTOM2,
      GNSD_JOBS.CUSTOM3,
      GNSD_JOBS.STEP,
      GNSD_JOBS.STATUS,
      GNSD_JOBS.NEEDSPROCESSING,
      GNSD_JOBS.ISACTIVE,
      GNSD_JOBS.PROCESSID,
      GNSD_JOBS.PROCESSING_USERID,
      GNSD_JOBS.PROCESSOR_CLASSID,
      GNSD_JOBS.ISARCHIVED,
      GNSD_JOBS.PERIODBEGINDATE, 
      GNSD_JOBS.PERIODENDDATE,
      GNSD_JOBS.DESCRIPTION,
      GNSD_JOBS.PARCELNUMBER,
      GNSD_JOBS.MUNICIPALITY,
      GNSD_JOBS.CENTERAREAX,
      GNSD_JOBS.CENTERAREAY,
      GNSD_JOBS.DOWNLOADCOUNT,
      GNSD_JOBS.MAPEXTENTCOUNT,
      GNSD_SURROGATE_JOBS.SURROGATEUSERID,
      GNSD_SURROGATE_JOBS.REQUESTDATE,
      GNSD_SURROGATE_JOBS.REQUESTTYPE,
      GNSD_SURROGATE_JOBS.STOPAFTERPROCESS,
      GNSD_USERS.FIRSTNAME,
      GNSD_USERS.LASTNAME,
      GNSD_USERS.EMAIL
      FROM
      ((GNSD_JOBS left outer join
      (SELECT
      GNSD_JOBS_LOG.JOBID AS ID,
      MAX(TIMESTAMP) AS STATEDATE,
      MIN(TIMESTAMP) AS CREATEDATE
      FROM
      GNSD_JOBS_LOG
      GROUP BY
      JOBID) AS LOGS on GNSD_JOBS.JOBID = LOGS.ID)
        left outer join GNSD_USERS on GNSD_JOBS.USERID = GNSD_USERS.USERID) 
        left outer join GNSD_REASONS on GNSD_JOBS.REASONID = GNSD_REASONS.REASONID
        left outer join GNSD_SURROGATE_JOBS on GNSD_JOBS.JOBID = GNSD_SURROGATE_JOBS.JOBID

GO


SET ANSI_PADDING OFF
GO


