CREATE TABLE GNSD_BIZ_USERS
(
  EMAIL VARCHAR2(128) NOT NULL,
  PASSWORD VARCHAR2(250),
  ROLES VARCHAR2(4000),
  STATUS INTEGER
, CONSTRAINT GNSD_BIZ_USER_PK PRIMARY KEY
  (
    EMAIL
  )
)
;
 CREATE SEQUENCE GNSD_BIZ_USERS_SEQ ;

CREATE VIEW GNSD_GRIDJOBVIEW AS SELECT 
    GNSD_JOBS.JOBID, 
    STATEDATE, 
    CREATEDATE, 
    GNSD_JOBS.USERID, 
    GNSD_JOBS.REASONID, 
    GNSDS_REASONS.DESCRIPTION,
    GNSD_JOBS.JOBOUTPUT, 
    GNSD_JOBS.DEFINITION, 
    GNSD_JOBS.STATUS, 
    GNSD_JOBS.PROCESSID, 
    GNSD_JOBS.PROCESSING_USERID, 
    GNSD_JOBS.PROCESSOR_CLASSID, 
    GNSD_USERS.FIRSTNAME, 
    GNSD_USERS.LASTNAME,
    GNSD_USERS.EMAIL 
FROM 
((GNSD_JOBS left outer join 
    (SELECT 
        GNSD_JOBS_LOG.JOBID AS ID, 
        MAX(TIMESTAMP) AS STATEDATE, 
        MIN(TIMESTAMP) AS CREATEDATE 
    FROM 
        GNSD_JOBS_LOG 
    GROUP BY 
        JOBID) on GNSD_JOBS.JOBID = ID) left outer join GNSD_USERS on GNSD_JOBS.USERID = GNSD_USERS.USERID) left outer join GNSDS_REASONS on GNSD_JOBS.REASONID = GNSDS_REASONS.REASONID;