ALTER TABLE GNSD_JOBS 
ADD ("ISARCHIVED" CHAR(1 CHAR) DEFAULT 'N' NOT NULL)
;

COMMENT ON COLUMN GNSD_JOBS."ISARCHIVED" IS '0=not archived 0!=archived'
;

CREATE OR REPLACE VIEW GNSD_GRIDJOBVIEW AS SELECT 
    GNSD_JOBS.JOBID, 
    STATEDATE, 
    CREATEDATE, 
    GNSD_JOBS.USERID, 
    GNSD_JOBS.REASONID, 
    GNSDS_REASONS.DESCRIPTION,
    GNSD_JOBS.JOBOUTPUT, 
    GNSD_JOBS.DEFINITION, 
    GNSD_JOBS.STATUS, 
    GNSD_JOBS.PROCESSID, 
    GNSD_JOBS.PROCESSING_USERID, 
    GNSD_JOBS.PROCESSOR_CLASSID, 
    GNSD_JOBS.ISARCHIVED,
    GNSD_USERS.FIRSTNAME, 
    GNSD_USERS.LASTNAME,
    GNSD_USERS.EMAIL 
FROM 
((GNSD_JOBS left outer join 
    (SELECT 
        GNSD_JOBS_LOG.JOBID AS ID, 
        MAX(TIMESTAMP) AS STATEDATE, 
        MIN(TIMESTAMP) AS CREATEDATE 
    FROM 
        GNSD_JOBS_LOG 
    GROUP BY 
        JOBID) on GNSD_JOBS.JOBID = ID) left outer join GNSD_USERS on GNSD_JOBS.USERID = GNSD_USERS.USERID) left outer join GNSDS_REASONS on GNSD_JOBS.REASONID = GNSDS_REASONS.REASONID;

ALTER TABLE GNSD_BIZ_USERS 
ADD ("PASSWORDSALT" VARCHAR2(50))
;



