ALTER TABLE GNSD_BIZ_USERS 
ADD ("BIZUSERID" NUMBER(10, 0) NOT NULL)
;

ALTER TABLE GNSD_BIZ_USERS 
DROP CONSTRAINT "GNSD_BIZ_USER_PK"
;

ALTER TABLE GNSD_BIZ_USERS 
ADD CONSTRAINT GNSD_BIZ_USER_PK PRIMARY KEY 
(
"BIZUSERID"
) ENABLE
;

ALTER TABLE GNSD_USERS 
ADD ("BIZUSER" NUMBER(10, 0) )
;

ALTER TABLE GNSD_BIZ_USERS 
DROP COLUMN "EMAIL"
;

