ALTER TABLE GNSD_JOBS 
ADD ("FREE1" VARCHAR2(256));

ALTER TABLE GNSD_JOBS 
ADD ("FREE2" VARCHAR2(256));

CREATE OR REPLACE VIEW GNSD_GRIDJOBVIEW AS SELECT 
    GNSD_JOBS.JOBID, 
    STATEDATE, 
    CREATEDATE, 
    GNSD_JOBS.USERID, 
    GNSD_JOBS.REASONID, 
    GNSD_REASONS.DESCRIPTION,
    GNSD_JOBS.JOBOUTPUT, 
    GNSD_JOBS.DEFINITION, 
    GNSD_JOBS.FREE1,
    GNSD_JOBS.FREE2,
    GNSD_JOBS.STATUS, 
    GNSD_JOBS.PROCESSID, 
    GNSD_JOBS.PROCESSING_USERID, 
    GNSD_JOBS.PROCESSOR_CLASSID, 
    GNSD_JOBS.ISARCHIVED,
    GNSD_USERS.FIRSTNAME, 
    GNSD_USERS.LASTNAME,
    GNSD_USERS.EMAIL
FROM 
((GNSD_JOBS left outer join 
    (SELECT 
        GNSD_JOBS_LOG.JOBID AS ID, 
        MAX(TIMESTAMP) AS STATEDATE, 
        MIN(TIMESTAMP) AS CREATEDATE 
    FROM 
        GNSD_JOBS_LOG 
    GROUP BY 
        JOBID) on GNSD_JOBS.JOBID = ID) left outer join GNSD_USERS on GNSD_JOBS.USERID = GNSD_USERS.USERID) left outer join GNSD_REASONS on GNSD_JOBS.REASONID = GNSD_REASONS.REASONID;

