using System;
using GEOCOM.GNSD.Web.Config;

namespace GEOCOM.GNSD.Web.Controls
{
    public partial class DataModeMap : MapBase
    {
        #region Public Properties

        /// <summary>
        /// The javascript call to the toolbar constructor is generated by the dsToolbar control
        /// </summary>
        public string TbCreator
        {
            get { return this._toolbarCreator; }
        }

        /// <summary>
        /// The javascript call to the toolbar initializer is generated by tjhe dsPdeToolbar control
        /// </summary>
        public string TbPageLoad
        {
            get { return this._toolbarPageLoad; }
        }

        public float MaxSelectableArea 
        {
            get { return DatashopWebConfig.Instance.MapService.MaxSelectableArea; }
        }

        public string GeometryServiceUrl
        {
            get { return DatashopWebConfig.Instance.MapService.GeometryServiceUrl; }
        }

        #endregion

        #region Private variable

        private string _toolbarCreator;

        private string _toolbarPageLoad;

        #endregion

        protected void Page_Load(object sender, EventArgs e)
        {
            // create the toolbar
            var toolbarPde = new Controls.DsPdeToolbar(
                "tbPde",
                MaxPolygons,
                null,
                divDsToolbar,
                divDsToolbar,
                "btnOut btnUnpressed",
                "btnIn ",
                "btnOut btnHover",
                "btnIn ",
                "btnOut btnPressed",
                "btnIn ",
                "btnOut btnSelected",
                "btnIn ",
                "btnOut",
                "btnIn btnDisabled_",
                DatashopWebConfig.Instance.RequestPageConfig.DataMode.WithCreateRectangle,
                DatashopWebConfig.Instance.RequestPageConfig.DataMode.WithCreatePolygon);
            this._toolbarCreator = toolbarPde.JsCreator;
            this._toolbarPageLoad = toolbarPde.JsPageLoad;

            HandleLoadingPreviousMapExtents();
        }

       
    }
}